controller_list:
  - name: fake_head_controller
    joints:
      - head_roll_joint
      - head_tilt_joint
      - head_pan_joint
  - name: fake_eyes_controller
    joints:
      - eyes_pan_joint
  - name: fake_jaw_controller
    joints:
      - jaw_joint